- name: Install aptitude using apt
  apt:
    name: aptitude
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Ensure "wheel" group present
  group:
    name: wheel
    state: present

- name: Allow "wheel" group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

- name: Create "barbossa" user
  user:
    name: barbossa
    groups:
      - wheel
    append: yes
    state: present
    createhome: yes
    uid: 1002
    shell: /usr/bin/bash

- name: Add authorized key to "barbossa"
  authorized_key:
    user: barbossa
    key: "{{item}}"
  with_file:
    - ~/.ssh/id_rsa.pub

- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    [
      "python3-setuptools",
      "apt-transport-https",
      "ca-certificates",
      "curl",
      "software-properties-common",
      "python3",
      "python3-pip",
      "virtualenv",
      "python-pip",
      "python-setuptools",
    ]

- name: Install pip dependencies
  pip:
    name: "{{ item }}"
    state: present
    executable: pip3
  loop: ["jsondiff", "pyyaml", "docker", "docker-compose"]

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install docker-ce
  apt:
    update_cache: yes
    name: docker-ce
    state: latest

- name: Create configuration directory
  file:
    path: "/etc/barbossa"
    state: directory
    mode: "0755"
    owner: barbossa
    group: barbossa

- name: Create media directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: barbossa
    group: barbossa
  loop:
    [
      "{{ nfs_mount }}/downloads",
      "{{ nfs_mount }}/incomplete-downloads",
      "{{ nfs_mount }}/media",
    ]

- name: Run docker-compose
  docker_compose:
    project_src: /opt/barbossa

- name: Fix data directory permissions
  file:
    path: "{{ nfs_mount }}"
    state: directory
    mode: "0755"
    owner: barbossa
    group: barbossa
    recurse: yes
